# Generated by Django 4.0.4 on 2022-06-19 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_neighbourhood_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='hood', to='app.profile'),
        ),
    ]
