# Generated by Django 4.0.4 on 2022-06-21 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post'),
        ('business', '0002_membership_business_neighbourhood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.profile', verbose_name='Business Owner'),
        ),
    ]
